export interface CountryState {
  code: string
  name: string
}

export interface CountryInfo {
  code: string
  name: string
  visa_support: boolean
  eor_support: boolean
  state_type: string | null
  states: CountryState[]
}

export interface Currency {
  code: string
  name: string
}

// Country to currency mapping
export const countryCurrencyMapping: Record<string, string> = {
  AE: "AED",
  AL: "ALL",
  AM: "AMD",
  AR: "ARS",
  AT: "EUR",
  AU: "AUD",
  AZ: "AZN",
  BA: "BAM",
  BD: "BDT",
  BE: "EUR",
  BG: "BGN",
  BH: "BHD",
  BO: "BOB",
  BR: "BRL",
  CA: "CAD",
  CH: "CHF",
  CI: "XOF",
  CL: "CLP",
  CM: "XAF",
  CN: "CNY",
  CO: "COP",
  CR: "CRC",
  CY: "EUR",
  CZ: "CZK",
  DE: "EUR",
  DK: "DKK",
  DO: "DOP",
  EC: "USD",
  EE: "EUR",
  EG: "EGP",
  ES: "EUR",
  ET: "ETB",
  FI: "EUR",
  FR: "EUR",
  GB: "GBP",
  GE: "GEL",
  GH: "GHS",
  GR: "EUR",
  GT: "GTQ",
  HK: "HKD",
  HN: "HNL",
  HR: "EUR",
  HU: "HUF",
  ID: "IDR",
  IE: "EUR",
  IL: "ILS",
  IN: "INR",
  IS: "ISK",
  IT: "EUR",
  JM: "JMD",
  JO: "JOD",
  JP: "JPY",
  KE: "KES",
  KH: "KHR",
  KR: "KRW",
  KZ: "KZT",
  LK: "LKR",
  LT: "EUR",
  LU: "EUR",
  LV: "EUR",
  MA: "MAD",
  MD: "MDL",
  ME: "EUR",
  MG: "MGA",
  MK: "MKD",
  MN: "MNT",
  MT: "EUR",
  MU: "MUR",
  MX: "MXN",
  MY: "MYR",
  MZ: "MZN",
  NA: "NAD",
  NG: "NGN",
  NI: "NIO",
  NL: "EUR",
  NO: "NOK",
  NP: "NPR",
  NZ: "NZD",
  OM: "OMR",
  PA: "USD",
  PE: "PEN",
  PH: "PHP",
  PK: "PKR",
  PL: "PLN",
  PR: "USD",
  PT: "EUR",
  PY: "PYG",
  QA: "QAR",
  RO: "RON",
  RS: "RSD",
  RW: "RWF",
  SA: "SAR",
  SE: "SEK",
  SG: "SGD",
  SI: "EUR",
  SK: "EUR",
  SN: "XOF",
  SV: "USD",
  TH: "THB",
  TN: "TND",
  TR: "TRY",
  TW: "TWD",
  UA: "UAH",
  UG: "UGX",
  US: "USD",
  UY: "UYU",
  UZ: "UZS",
  VE: "VES",
  VN: "VND",
  ZA: "ZAR",
  ZM: "ZMW",
  ZW: "ZWG",
}

// Currency data
export const allCurrencies: Currency[] = [
  { code: "AED", name: "United Arab Emirates Dirham" },
  { code: "AFN", name: "Afghani" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "AOA", name: "Kwanza" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "BIF", name: "Burundi Franc" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BTN", name: "Ngultrum" },
  { code: "BWP", name: "Pula" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "COP", name: "Colombian Peso" },
  { code: "CRC", name: "Costa Rican Colon" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "CVE", name: "Cape Verdean Escudo" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "DKK", name: "Danish Krone" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "ERN", name: "Eritrean Nakfa" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "EUR", name: "Euro" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "FKP", name: "Falkland Islands Pound" },
  { code: "GBP", name: "British Pound" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "GIP", name: "Gibraltar Pound" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "GNF", name: "Guinea Franc" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "GYD", name: "Guyanese Dollar" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "INR", name: "Indian Rupee" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "KPW", name: "North Korean Won" },
  { code: "KRW", name: "South Korean Won" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "LAK", name: "Kip" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "LTL", name: "Lithuania Litas" },
  { code: "LVL", name: "Latvian Lats" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "MMK", name: "Burmese Kyat" },
  { code: "MNT", name: "Mongolian Tögrög" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "MRO", name: "Mauritanian Ouguiya" },
  { code: "MRU", name: "Mauritanian Ouguiya" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MWK", name: "Malawian Kwacha" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "NAD", name: "Namibia Dollar" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "PGK", name: "Kina" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "PLN", name: "Polish Złoty" },
  { code: "PYG", name: "Paraguayan Guarani" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "SCR", name: "Seychellois Rupee" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "SHP", name: "Saint Helena Pound" },
  { code: "SLL", name: "Sierra Leonean Leone" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "STN", name: "São Tomé and Príncipe Dobra" },
  { code: "SVC", name: "Salvadoran Colón" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "SZL", name: "Swazi Lilangeni" },
  { code: "THB", name: "Thai Baht" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "TMT", name: "Turkmenistan Manat" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "TOP", name: "Tongan Paʻanga" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "USD", name: "US Dollar" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "UZS", name: "Uzbekistani Soum" },
  { code: "VES", name: "Venezuelan Bolívar Soberano" },
  { code: "VND", name: "Vietnamese Dồng" },
  { code: "VUV", name: "Vanuatu Vatu" },
  { code: "WST", name: "Samoan Tālā" },
  { code: "XAF", name: "Central African CFA franc" },
  { code: "XAG", name: "Silver" },
  { code: "XAU", name: "Gold" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XPF", name: "CFP Franc" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZAR", name: "South African Rand" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWL", name: "Zimbabwean Dollar" },
]

// Countries data - comprehensive list with states/provinces
export const allCountries: CountryInfo[] = [
  {
    code: "AD",
    name: "Andorra",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    visa_support: true,
    eor_support: true,
    state_type: "emirate",
    states: [
      { code: "AZ", name: "Abu Dhabi" },
      { code: "AJ", name: "Ajman" },
      { code: "DU", name: "Dubai" },
      { code: "FU", name: "Fujairah" },
      { code: "RA", name: "Ras al-Khaimah" },
      { code: "SH", name: "Sharjah" },
      { code: "UQ", name: "Umm al-Quwain" },
    ],
  },
  {
    code: "AF",
    name: "Afghanistan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AI",
    name: "Anguilla",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AL",
    name: "Albania",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "AM",
    name: "Armenia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "AO",
    name: "Angola",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AQ",
    name: "Antarctica",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AR",
    name: "Argentina",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "C", name: "Ciudad Autónoma de Buenos Aires" },
      { code: "B", name: "Buenos Aires" },
      { code: "K", name: "Catamarca" },
      { code: "H", name: "Chaco" },
      { code: "U", name: "Chubut" },
      { code: "X", name: "Córdoba" },
      { code: "W", name: "Corrientes" },
      { code: "E", name: "Entre Ríos" },
      { code: "P", name: "Formosa" },
      { code: "Y", name: "Jujuy" },
      { code: "L", name: "La Pampa" },
      { code: "F", name: "La Rioja" },
      { code: "M", name: "Mendoza" },
      { code: "N", name: "Misiones" },
      { code: "Q", name: "Neuquén" },
      { code: "R", name: "Río Negro" },
      { code: "A", name: "Salta" },
      { code: "J", name: "San Juan" },
      { code: "D", name: "San Luis" },
      { code: "Z", name: "Santa Cruz" },
      { code: "S", name: "Santa Fe" },
      { code: "G", name: "Santiago del Estero" },
      { code: "V", name: "Tierra del Fuego" },
      { code: "T", name: "Tucumán" },
    ],
  },
  {
    code: "AS",
    name: "American Samoa",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AT",
    name: "Austria",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "1", name: "Burgenland" },
      { code: "2", name: "Kärnten" },
      { code: "3", name: "Niederösterreich" },
      { code: "4", name: "Oberösterreich" },
      { code: "5", name: "Salzburg" },
      { code: "6", name: "Steiermark" },
      { code: "7", name: "Tirol" },
      { code: "8", name: "Vorarlberg" },
      { code: "9", name: "Wien" },
    ],
  },
  {
    code: "AU",
    name: "Australia",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "ACT", name: "Australian Capital Territory" },
      { code: "NSW", name: "New South Wales" },
      { code: "NT", name: "Northern Territory" },
      { code: "QLD", name: "Queensland" },
      { code: "SA", name: "South Australia" },
      { code: "TAS", name: "Tasmania" },
      { code: "VIC", name: "Victoria" },
      { code: "WA", name: "Western Australia" },
    ],
  },
  {
    code: "AW",
    name: "Aruba",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AX",
    name: "Åland Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BB",
    name: "Barbados",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BD",
    name: "Bangladesh",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BE",
    name: "Belgium",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "BRU", name: "Brussels-Capital Region" },
      { code: "VLG", name: "Flemish Region" },
      { code: "WAL", name: "Walloon Region" },
    ],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BG",
    name: "Bulgaria",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BH",
    name: "Bahrain",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BI",
    name: "Burundi",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BJ",
    name: "Benin",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BM",
    name: "Bermuda",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BO",
    name: "Bolivia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BR",
    name: "Brazil",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "AC", name: "Acre" },
      { code: "AL", name: "Alagoas" },
      { code: "AP", name: "Amapá" },
      { code: "AM", name: "Amazonas" },
      { code: "BA", name: "Bahia" },
      { code: "CE", name: "Ceará" },
      { code: "DF", name: "Distrito Federal" },
      { code: "ES", name: "Espírito Santo" },
      { code: "GO", name: "Goiás" },
      { code: "MA", name: "Maranhão" },
      { code: "MT", name: "Mato Grosso" },
      { code: "MS", name: "Mato Grosso do Sul" },
      { code: "MG", name: "Minas Gerais" },
      { code: "PA", name: "Pará" },
      { code: "PB", name: "Paraíba" },
      { code: "PR", name: "Paraná" },
      { code: "PE", name: "Pernambuco" },
      { code: "PI", name: "Piauí" },
      { code: "RJ", name: "Rio de Janeiro" },
      { code: "RN", name: "Rio Grande do Norte" },
      { code: "RS", name: "Rio Grande do Sul" },
      { code: "RO", name: "Rondônia" },
      { code: "RR", name: "Roraima" },
      { code: "SC", name: "Santa Catarina" },
      { code: "SP", name: "São Paulo" },
      { code: "SE", name: "Sergipe" },
      { code: "TO", name: "Tocantins" },
    ],
  },
  {
    code: "BS",
    name: "Bahamas",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BT",
    name: "Bhutan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BV",
    name: "Bouvet Island",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BW",
    name: "Botswana",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BY",
    name: "Belarus",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "BZ",
    name: "Belize",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CA",
    name: "Canada",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "AB", name: "Alberta" },
      { code: "BC", name: "British Columbia" },
      { code: "MB", name: "Manitoba" },
      { code: "NB", name: "New Brunswick" },
      { code: "NL", name: "Newfoundland and Labrador" },
      { code: "NT", name: "Northwest Territories" },
      { code: "NS", name: "Nova Scotia" },
      { code: "NU", name: "Nunavut" },
      { code: "ON", name: "Ontario" },
      { code: "PE", name: "Prince Edward Island" },
      { code: "QC", name: "Quebec" },
      { code: "SK", name: "Saskatchewan" },
      { code: "YT", name: "Yukon" },
    ],
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CF",
    name: "Central African Republic",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CG",
    name: "Congo",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CH",
    name: "Switzerland",
    visa_support: true,
    eor_support: true,
    state_type: "canton",
    states: [
      { code: "AG", name: "Aargau" },
      { code: "AI", name: "Appenzell Innerrhoden" },
      { code: "AR", name: "Appenzell Ausserrhoden" },
      { code: "BE", name: "Bern" },
      { code: "BL", name: "Basel-Landschaft" },
      { code: "BS", name: "Basel-Stadt" },
      { code: "FR", name: "Fribourg" },
      { code: "GE", name: "Geneva" },
      { code: "GL", name: "Glarus" },
      { code: "GR", name: "Graubünden" },
      { code: "JU", name: "Jura" },
      { code: "LU", name: "Lucerne" },
      { code: "NE", name: "Neuchâtel" },
      { code: "NW", name: "Nidwalden" },
      { code: "OW", name: "Obwalden" },
      { code: "SG", name: "St. Gallen" },
      { code: "SH", name: "Schaffhausen" },
      { code: "SO", name: "Solothurn" },
      { code: "SZ", name: "Schwyz" },
      { code: "TG", name: "Thurgau" },
      { code: "TI", name: "Ticino" },
      { code: "UR", name: "Uri" },
      { code: "VD", name: "Vaud" },
      { code: "VS", name: "Valais" },
      { code: "ZG", name: "Zug" },
      { code: "ZH", name: "Zurich" },
    ],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CK",
    name: "Cook Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CL",
    name: "Chile",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "AI", name: "Aisén del General Carlos Ibáñez del Campo" },
      { code: "AN", name: "Antofagasta" },
      { code: "AP", name: "Arica y Parinacota" },
      { code: "AR", name: "Araucanía" },
      { code: "AT", name: "Atacama" },
      { code: "BI", name: "Biobío" },
      { code: "CO", name: "Coquimbo" },
      { code: "LI", name: "Libertador General Bernardo O'Higgins" },
      { code: "LL", name: "Los Lagos" },
      { code: "LR", name: "Los Ríos" },
      { code: "MA", name: "Magallanes y de la Antártica Chilena" },
      { code: "ML", name: "Maule" },
      { code: "NB", name: "Ñuble" },
      { code: "RM", name: "Región Metropolitana de Santiago" },
      { code: "TA", name: "Tarapacá" },
      { code: "VS", name: "Valparaíso" },
    ],
  },
  {
    code: "CM",
    name: "Cameroon",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CN",
    name: "China",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "AH", name: "Anhui" },
      { code: "BJ", name: "Beijing" },
      { code: "CQ", name: "Chongqing" },
      { code: "FJ", name: "Fujian" },
      { code: "GS", name: "Gansu" },
      { code: "GD", name: "Guangdong" },
      { code: "GX", name: "Guangxi" },
      { code: "GZ", name: "Guizhou" },
      { code: "HI", name: "Hainan" },
      { code: "HE", name: "Hebei" },
      { code: "HL", name: "Heilongjiang" },
      { code: "HA", name: "Henan" },
      { code: "HB", name: "Hubei" },
      { code: "HN", name: "Hunan" },
      { code: "JS", name: "Jiangsu" },
      { code: "JX", name: "Jiangxi" },
      { code: "JL", name: "Jilin" },
      { code: "LN", name: "Liaoning" },
      { code: "NM", name: "Inner Mongolia" },
      { code: "NX", name: "Ningxia" },
      { code: "QH", name: "Qinghai" },
      { code: "SN", name: "Shaanxi" },
      { code: "SD", name: "Shandong" },
      { code: "SH", name: "Shanghai" },
      { code: "SX", name: "Shanxi" },
      { code: "SC", name: "Sichuan" },
      { code: "TJ", name: "Tianjin" },
      { code: "XZ", name: "Tibet" },
      { code: "XJ", name: "Xinjiang" },
      { code: "YN", name: "Yunnan" },
      { code: "ZJ", name: "Zhejiang" },
    ],
  },
  {
    code: "CO",
    name: "Colombia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "CR",
    name: "Costa Rica",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "CU",
    name: "Cuba",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CV",
    name: "Cabo Verde",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CW",
    name: "Curaçao",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CX",
    name: "Christmas Island",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "CY",
    name: "Cyprus",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "CZ",
    name: "Czech Republic",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "DE",
    name: "Germany",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "BW", name: "Baden-Württemberg" },
      { code: "BY", name: "Bavaria" },
      { code: "BE", name: "Berlin" },
      { code: "BB", name: "Brandenburg" },
      { code: "HB", name: "Bremen" },
      { code: "HH", name: "Hamburg" },
      { code: "HE", name: "Hesse" },
      { code: "MV", name: "Mecklenburg-Vorpommern" },
      { code: "NI", name: "Lower Saxony" },
      { code: "NW", name: "North Rhine-Westphalia" },
      { code: "RP", name: "Rhineland-Palatinate" },
      { code: "SL", name: "Saarland" },
      { code: "SN", name: "Saxony" },
      { code: "ST", name: "Saxony-Anhalt" },
      { code: "SH", name: "Schleswig-Holstein" },
      { code: "TH", name: "Thuringia" },
    ],
  },
  {
    code: "DJ",
    name: "Djibouti",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "DK",
    name: "Denmark",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "DM",
    name: "Dominica",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "DO",
    name: "Dominican Republic",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "DZ",
    name: "Algeria",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "EC",
    name: "Ecuador",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "EE",
    name: "Estonia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "EG",
    name: "Egypt",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "EH",
    name: "Western Sahara",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "ER",
    name: "Eritrea",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "ES",
    name: "Spain",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "AN", name: "Andalusia" },
      { code: "AR", name: "Aragon" },
      { code: "AS", name: "Asturias" },
      { code: "IB", name: "Balearic Islands" },
      { code: "PV", name: "Basque Country" },
      { code: "CN", name: "Canary Islands" },
      { code: "CB", name: "Cantabria" },
      { code: "CM", name: "Castile-La Mancha" },
      { code: "CL", name: "Castile and León" },
      { code: "CT", name: "Catalonia" },
      { code: "CE", name: "Ceuta" },
      { code: "EX", name: "Extremadura" },
      { code: "GA", name: "Galicia" },
      { code: "RI", name: "La Rioja" },
      { code: "MD", name: "Madrid" },
      { code: "ML", name: "Melilla" },
      { code: "MC", name: "Murcia" },
      { code: "NC", name: "Navarre" },
      { code: "VC", name: "Valencia" },
    ],
  },
  {
    code: "ET",
    name: "Ethiopia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "FI",
    name: "Finland",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "FJ",
    name: "Fiji",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "FM",
    name: "Micronesia, Federated States of",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "FO",
    name: "Faroe Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "FR",
    name: "France",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "ARA", name: "Auvergne-Rhône-Alpes" },
      { code: "BFC", name: "Bourgogne-Franche-Comté" },
      { code: "BRE", name: "Brittany" },
      { code: "CVL", name: "Centre-Val de Loire" },
      { code: "COR", name: "Corsica" },
      { code: "GES", name: "Grand Est" },
      { code: "HDF", name: "Hauts-de-France" },
      { code: "IDF", name: "Île-de-France" },
      { code: "NOR", name: "Normandy" },
      { code: "NAQ", name: "Nouvelle-Aquitaine" },
      { code: "OCC", name: "Occitania" },
      { code: "PDL", name: "Pays de la Loire" },
      { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
    ],
  },
  {
    code: "GA",
    name: "Gabon",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GB",
    name: "United Kingdom",
    visa_support: true,
    eor_support: true,
    state_type: "country",
    states: [
      { code: "ENG", name: "England" },
      { code: "NIR", name: "Northern Ireland" },
      { code: "SCT", name: "Scotland" },
      { code: "WLS", name: "Wales" },
    ],
  },
  {
    code: "GD",
    name: "Grenada",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GE",
    name: "Georgia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "GF",
    name: "French Guiana",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GG",
    name: "Guernsey",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GH",
    name: "Ghana",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "GI",
    name: "Gibraltar",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GL",
    name: "Greenland",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GM",
    name: "Gambia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GN",
    name: "Guinea",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GP",
    name: "Guadeloupe",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GR",
    name: "Greece",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GT",
    name: "Guatemala",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "GU",
    name: "Guam",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "GY",
    name: "Guyana",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "HK",
    name: "Hong Kong",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "HN",
    name: "Honduras",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "HR",
    name: "Croatia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "HT",
    name: "Haiti",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "HU",
    name: "Hungary",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "ID",
    name: "Indonesia",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "AC", name: "Aceh" },
      { code: "SU", name: "North Sumatra" },
      { code: "SB", name: "West Sumatra" },
      { code: "RI", name: "Riau" },
      { code: "KR", name: "Riau Islands" },
      { code: "JA", name: "Jambi" },
      { code: "SS", name: "South Sumatra" },
      { code: "BB", name: "Bangka Belitung Islands" },
      { code: "BE", name: "Bengkulu" },
      { code: "LA", name: "Lampung" },
      { code: "JK", name: "Jakarta" },
      { code: "JB", name: "West Java" },
      { code: "BT", name: "Banten" },
      { code: "JT", name: "Central Java" },
      { code: "YO", name: "Yogyakarta" },
      { code: "JI", name: "East Java" },
      { code: "BA", name: "Bali" },
      { code: "NB", name: "West Nusa Tenggara" },
      { code: "NT", name: "East Nusa Tenggara" },
      { code: "KB", name: "West Kalimantan" },
      { code: "KT", name: "Central Kalimantan" },
      { code: "KS", name: "South Kalimantan" },
      { code: "KI", name: "East Kalimantan" },
      { code: "KU", name: "North Kalimantan" },
      { code: "SA", name: "North Sulawesi" },
      { code: "ST", name: "Central Sulawesi" },
      { code: "SG", name: "Southeast Sulawesi" },
      { code: "SR", name: "West Sulawesi" },
      { code: "SN", name: "South Sulawesi" },
      { code: "GO", name: "Gorontalo" },
      { code: "MA", name: "Maluku" },
      { code: "MU", name: "North Maluku" },
      { code: "PA", name: "Papua" },
      { code: "PB", name: "West Papua" },
    ],
  },
  {
    code: "IE",
    name: "Ireland",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "IL",
    name: "Israel",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "IM",
    name: "Isle of Man",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "IN",
    name: "India",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "AP", name: "Andhra Pradesh" },
      { code: "AR", name: "Arunachal Pradesh" },
      { code: "AS", name: "Assam" },
      { code: "BR", name: "Bihar" },
      { code: "CT", name: "Chhattisgarh" },
      { code: "GA", name: "Goa" },
      { code: "GJ", name: "Gujarat" },
      { code: "HR", name: "Haryana" },
      { code: "HP", name: "Himachal Pradesh" },
      { code: "JH", name: "Jharkhand" },
      { code: "KA", name: "Karnataka" },
      { code: "KL", name: "Kerala" },
      { code: "MP", name: "Madhya Pradesh" },
      { code: "MH", name: "Maharashtra" },
      { code: "MN", name: "Manipur" },
      { code: "ML", name: "Meghalaya" },
      { code: "MZ", name: "Mizoram" },
      { code: "NL", name: "Nagaland" },
      { code: "OR", name: "Odisha" },
      { code: "PB", name: "Punjab" },
      { code: "RJ", name: "Rajasthan" },
      { code: "SK", name: "Sikkim" },
      { code: "TN", name: "Tamil Nadu" },
      { code: "TG", name: "Telangana" },
      { code: "TR", name: "Tripura" },
      { code: "UP", name: "Uttar Pradesh" },
      { code: "UT", name: "Uttarakhand" },
      { code: "WB", name: "West Bengal" },
      { code: "AN", name: "Andaman and Nicobar Islands" },
      { code: "CH", name: "Chandigarh" },
      { code: "DN", name: "Dadra and Nagar Haveli and Daman and Diu" },
      { code: "DL", name: "Delhi" },
      { code: "JK", name: "Jammu and Kashmir" },
      { code: "LA", name: "Ladakh" },
      { code: "LD", name: "Lakshadweep" },
      { code: "PY", name: "Puducherry" },
    ],
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "IQ",
    name: "Iraq",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "IR",
    name: "Iran, Islamic Republic of",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "IS",
    name: "Iceland",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "IT",
    name: "Italy",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "65", name: "Abruzzo" },
      { code: "77", name: "Basilicata" },
      { code: "78", name: "Calabria" },
      { code: "72", name: "Campania" },
      { code: "45", name: "Emilia-Romagna" },
      { code: "36", name: "Friuli-Venezia Giulia" },
      { code: "62", name: "Lazio" },
      { code: "42", name: "Liguria" },
      { code: "25", name: "Lombardy" },
      { code: "57", name: "Marche" },
      { code: "67", name: "Molise" },
      { code: "21", name: "Piedmont" },
      { code: "75", name: "Apulia" },
      { code: "88", name: "Sardinia" },
      { code: "82", name: "Sicily" },
      { code: "52", name: "Tuscany" },
      { code: "32", name: "Trentino-Alto Adige" },
      { code: "55", name: "Umbria" },
      { code: "23", name: "Aosta Valley" },
      { code: "34", name: "Veneto" },
    ],
  },
  {
    code: "JE",
    name: "Jersey",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "JM",
    name: "Jamaica",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "JO",
    name: "Jordan",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "JP",
    name: "Japan",
    visa_support: true,
    eor_support: true,
    state_type: "prefecture",
    states: [
      { code: "01", name: "Hokkaido" },
      { code: "02", name: "Aomori" },
      { code: "03", name: "Iwate" },
      { code: "04", name: "Miyagi" },
      { code: "05", name: "Akita" },
      { code: "06", name: "Yamagata" },
      { code: "07", name: "Fukushima" },
      { code: "08", name: "Ibaraki" },
      { code: "09", name: "Tochigi" },
      { code: "10", name: "Gunma" },
      { code: "11", name: "Saitama" },
      { code: "12", name: "Chiba" },
      { code: "13", name: "Tokyo" },
      { code: "14", name: "Kanagawa" },
      { code: "15", name: "Niigata" },
      { code: "16", name: "Toyama" },
      { code: "17", name: "Ishikawa" },
      { code: "18", name: "Fukui" },
      { code: "19", name: "Yamanashi" },
      { code: "20", name: "Nagano" },
      { code: "21", name: "Gifu" },
      { code: "22", name: "Shizuoka" },
      { code: "23", name: "Aichi" },
      { code: "24", name: "Mie" },
      { code: "25", name: "Shiga" },
      { code: "26", name: "Kyoto" },
      { code: "27", name: "Osaka" },
      { code: "28", name: "Hyogo" },
      { code: "29", name: "Nara" },
      { code: "30", name: "Wakayama" },
      { code: "31", name: "Tottori" },
      { code: "32", name: "Shimane" },
      { code: "33", name: "Okayama" },
      { code: "34", name: "Hiroshima" },
      { code: "35", name: "Yamaguchi" },
      { code: "36", name: "Tokushima" },
      { code: "37", name: "Kagawa" },
      { code: "38", name: "Ehime" },
      { code: "39", name: "Kochi" },
      { code: "40", name: "Fukuoka" },
      { code: "41", name: "Saga" },
      { code: "42", name: "Nagasaki" },
      { code: "43", name: "Kumamoto" },
      { code: "44", name: "Oita" },
      { code: "45", name: "Miyazaki" },
      { code: "46", name: "Kagoshima" },
      { code: "47", name: "Okinawa" },
    ],
  },
  {
    code: "KE",
    name: "Kenya",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KH",
    name: "Cambodia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "KI",
    name: "Kiribati",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KM",
    name: "Comoros",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KR",
    name: "Korea, Republic of",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "11", name: "Seoul" },
      { code: "26", name: "Busan" },
      { code: "27", name: "Daegu" },
      { code: "28", name: "Incheon" },
      { code: "29", name: "Gwangju" },
      { code: "30", name: "Daejeon" },
      { code: "31", name: "Ulsan" },
      { code: "50", name: "Sejong" },
      { code: "41", name: "Gyeonggi" },
      { code: "51", name: "Gangwon" },
      { code: "43", name: "North Chungcheong" },
      { code: "44", name: "South Chungcheong" },
      { code: "45", name: "North Jeolla" },
      { code: "46", name: "South Jeolla" },
      { code: "47", name: "North Gyeongsang" },
      { code: "48", name: "South Gyeongsang" },
      { code: "49", name: "Jeju" },
    ],
  },
  {
    code: "KW",
    name: "Kuwait",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KY",
    name: "Cayman Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LB",
    name: "Lebanon",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LC",
    name: "Saint Lucia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LI",
    name: "Liechtenstein",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "LR",
    name: "Liberia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LS",
    name: "Lesotho",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "LT",
    name: "Lithuania",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "LU",
    name: "Luxembourg",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "LV",
    name: "Latvia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "LY",
    name: "Libya",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MA",
    name: "Morocco",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MC",
    name: "Monaco",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MD",
    name: "Moldova, Republic of",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "ME",
    name: "Montenegro",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MG",
    name: "Madagascar",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MH",
    name: "Marshall Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MK",
    name: "North Macedonia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "ML",
    name: "Mali",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MM",
    name: "Myanmar",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MN",
    name: "Mongolia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MO",
    name: "Macao",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MQ",
    name: "Martinique",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MR",
    name: "Mauritania",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MS",
    name: "Montserrat",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MT",
    name: "Malta",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MU",
    name: "Mauritius",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "MV",
    name: "Maldives",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MW",
    name: "Malawi",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "MX",
    name: "Mexico",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "AGU", name: "Aguascalientes" },
      { code: "BCN", name: "Baja California" },
      { code: "BCS", name: "Baja California Sur" },
      { code: "CAM", name: "Campeche" },
      { code: "CHP", name: "Chiapas" },
      { code: "CHH", name: "Chihuahua" },
      { code: "CMX", name: "Ciudad de México" },
      { code: "COA", name: "Coahuila" },
      { code: "COL", name: "Colima" },
      { code: "DUR", name: "Durango" },
      { code: "GUA", name: "Guanajuato" },
      { code: "GRO", name: "Guerrero" },
      { code: "HID", name: "Hidalgo" },
      { code: "JAL", name: "Jalisco" },
      { code: "MEX", name: "México" },
      { code: "MIC", name: "Michoacán" },
      { code: "MOR", name: "Morelos" },
      { code: "NAY", name: "Nayarit" },
      { code: "NLE", name: "Nuevo León" },
      { code: "OAX", name: "Oaxaca" },
      { code: "PUE", name: "Puebla" },
      { code: "QUE", name: "Querétaro" },
      { code: "ROO", name: "Quintana Roo" },
      { code: "SLP", name: "San Luis Potosí" },
      { code: "SIN", name: "Sinaloa" },
      { code: "SON", name: "Sonora" },
      { code: "TAB", name: "Tabasco" },
      { code: "TAM", name: "Tamaulipas" },
      { code: "TLA", name: "Tlaxcala" },
      { code: "VER", name: "Veracruz" },
      { code: "YUC", name: "Yucatán" },
      { code: "ZAC", name: "Zacatecas" },
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "01", name: "Johor" },
      { code: "02", name: "Kedah" },
      { code: "03", name: "Kelantan" },
      { code: "04", name: "Malacca" },
      { code: "05", name: "Negeri Sembilan" },
      { code: "06", name: "Pahang" },
      { code: "07", name: "Penang" },
      { code: "08", name: "Perak" },
      { code: "09", name: "Perlis" },
      { code: "10", name: "Selangor" },
      { code: "11", name: "Terengganu" },
      { code: "12", name: "Sabah" },
      { code: "13", name: "Sarawak" },
      { code: "14", name: "Federal Territory of Kuala Lumpur" },
      { code: "15", name: "Federal Territory of Labuan" },
      { code: "16", name: "Federal Territory of Putrajaya" },
    ],
  },
  {
    code: "MZ",
    name: "Mozambique",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "NA",
    name: "Namibia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "NC",
    name: "New Caledonia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "NE",
    name: "Niger",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "NF",
    name: "Norfolk Island",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "NG",
    name: "Nigeria",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "AB", name: "Abia" },
      { code: "FC", name: "Abuja Federal Capital Territory" },
      { code: "AD", name: "Adamawa" },
      { code: "AK", name: "Akwa Ibom" },
      { code: "AN", name: "Anambra" },
      { code: "BA", name: "Bauchi" },
      { code: "BY", name: "Bayelsa" },
      { code: "BE", name: "Benue" },
      { code: "BO", name: "Borno" },
      { code: "CR", name: "Cross River" },
      { code: "DE", name: "Delta" },
      { code: "EB", name: "Ebonyi" },
      { code: "ED", name: "Edo" },
      { code: "EK", name: "Ekiti" },
      { code: "EN", name: "Enugu" },
      { code: "GO", name: "Gombe" },
      { code: "IM", name: "Imo" },
      { code: "JI", name: "Jigawa" },
      { code: "KD", name: "Kaduna" },
      { code: "KN", name: "Kano" },
      { code: "KT", name: "Katsina" },
      { code: "KE", name: "Kebbi" },
      { code: "KO", name: "Kogi" },
      { code: "KW", name: "Kwara" },
      { code: "LA", name: "Lagos" },
      { code: "NA", name: "Nasarawa" },
      { code: "NI", name: "Niger" },
      { code: "OG", name: "Ogun" },
      { code: "ON", name: "Ondo" },
      { code: "OS", name: "Osun" },
      { code: "OY", name: "Oyo" },
      { code: "PL", name: "Plateau" },
      { code: "RI", name: "Rivers" },
      { code: "SO", name: "Sokoto" },
      { code: "TA", name: "Taraba" },
      { code: "YO", name: "Yobe" },
      { code: "ZA", name: "Zamfara" },
    ],
  },
  {
    code: "NI",
    name: "Nicaragua",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "NL",
    name: "Netherlands",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "DR", name: "Drenthe" },
      { code: "FL", name: "Flevoland" },
      { code: "FR", name: "Friesland" },
      { code: "GE", name: "Gelderland" },
      { code: "GR", name: "Groningen" },
      { code: "LI", name: "Limburg" },
      { code: "NB", name: "North Brabant" },
      { code: "NH", name: "North Holland" },
      { code: "OV", name: "Overijssel" },
      { code: "UT", name: "Utrecht" },
      { code: "ZE", name: "Zeeland" },
      { code: "ZH", name: "South Holland" },
    ],
  },
  {
    code: "NO",
    name: "Norway",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "NP",
    name: "Nepal",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "NR",
    name: "Nauru",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "NU",
    name: "Niue",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "NZ",
    name: "New Zealand",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "AUK", name: "Auckland" },
      { code: "BOP", name: "Bay of Plenty" },
      { code: "CAN", name: "Canterbury" },
      { code: "GIS", name: "Gisborne" },
      { code: "HKB", name: "Hawke's Bay" },
      { code: "MWT", name: "Manawatu-Wanganui" },
      { code: "MBH", name: "Marlborough" },
      { code: "NSN", name: "Nelson" },
      { code: "NTL", name: "Northland" },
      { code: "OTA", name: "Otago" },
      { code: "STL", name: "Southland" },
      { code: "TKI", name: "Taranaki" },
      { code: "TAS", name: "Tasman" },
      { code: "WKO", name: "Waikato" },
      { code: "WGN", name: "Wellington" },
      { code: "WTC", name: "West Coast" },
    ],
  },
  {
    code: "OM",
    name: "Oman",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "PA",
    name: "Panama",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "PE",
    name: "Peru",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "PF",
    name: "French Polynesia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PH",
    name: "Philippines",
    visa_support: true,
    eor_support: true,
    state_type: "region",
    states: [
      { code: "14", name: "Autonomous Region in Muslim Mindanao" },
      { code: "05", name: "Bicol Region" },
      { code: "02", name: "Cagayan Valley" },
      { code: "40", name: "Calabarzon" },
      { code: "13", name: "Caraga" },
      { code: "03", name: "Central Luzon" },
      { code: "07", name: "Central Visayas" },
      { code: "15", name: "Cordillera Administrative Region" },
      { code: "11", name: "Davao Region" },
      { code: "08", name: "Eastern Visayas" },
      { code: "01", name: "Ilocos Region" },
      { code: "41", name: "Mimaropa" },
      { code: "00", name: "National Capital Region" },
      { code: "10", name: "Northern Mindanao" },
      { code: "12", name: "Soccsksargen" },
      { code: "06", name: "Western Visayas" },
      { code: "09", name: "Zamboanga Peninsula" },
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "JK", name: "Azad Jammu and Kashmir" },
      { code: "BA", name: "Balochistan" },
      { code: "TA", name: "Federally Administered Tribal Areas" },
      { code: "GB", name: "Gilgit-Baltistan" },
      { code: "IS", name: "Islamabad" },
      { code: "KP", name: "Khyber Pakhtunkhwa" },
      { code: "PB", name: "Punjab" },
      { code: "SD", name: "Sindh" },
    ],
  },
  {
    code: "PL",
    name: "Poland",
    visa_support: true,
    eor_support: true,
    state_type: "voivodeship",
    states: [
      { code: "02", name: "Lower Silesian Voivodeship" },
      { code: "04", name: "Kuyavian-Pomeranian Voivodeship" },
      { code: "06", name: "Lublin Voivodeship" },
      { code: "08", name: "Lubusz Voivodeship" },
      { code: "10", name: "Łódź Voivodeship" },
      { code: "12", name: "Lesser Poland Voivodeship" },
      { code: "14", name: "Masovian Voivodeship" },
      { code: "16", name: "Opole Voivodeship" },
      { code: "18", name: "Subcarpathian Voivodeship" },
      { code: "20", name: "Podlaskie Voivodeship" },
      { code: "22", name: "Pomeranian Voivodeship" },
      { code: "24", name: "Silesian Voivodeship" },
      { code: "26", name: "Holy Cross Voivodeship" },
      { code: "28", name: "Warmian-Masurian Voivodeship" },
      { code: "30", name: "Greater Poland Voivodeship" },
      { code: "32", name: "West Pomeranian Voivodeship" },
    ],
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PN",
    name: "Pitcairn",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "PS",
    name: "Palestine, State of",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PT",
    name: "Portugal",
    visa_support: true,
    eor_support: true,
    state_type: "district",
    states: [
      { code: "01", name: "Aveiro" },
      { code: "02", name: "Beja" },
      { code: "03", name: "Braga" },
      { code: "04", name: "Bragança" },
      { code: "05", name: "Castelo Branco" },
      { code: "06", name: "Coimbra" },
      { code: "07", name: "Évora" },
      { code: "08", name: "Faro" },
      { code: "09", name: "Guarda" },
      { code: "10", name: "Leiria" },
      { code: "11", name: "Lisboa" },
      { code: "12", name: "Portalegre" },
      { code: "13", name: "Porto" },
      { code: "14", name: "Santarém" },
      { code: "15", name: "Setúbal" },
      { code: "16", name: "Viana do Castelo" },
      { code: "17", name: "Vila Real" },
      { code: "18", name: "Viseu" },
      { code: "20", name: "Azores" },
      { code: "30", name: "Madeira" },
    ],
  },
  {
    code: "PW",
    name: "Palau",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "PY",
    name: "Paraguay",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "QA",
    name: "Qatar",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "RE",
    name: "Réunion",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "RO",
    name: "Romania",
    visa_support: true,
    eor_support: true,
    state_type: "county",
    states: [
      { code: "AB", name: "Alba" },
      { code: "AR", name: "Arad" },
      { code: "AG", name: "Argeș" },
      { code: "BC", name: "Bacău" },
      { code: "BH", name: "Bihor" },
      { code: "BN", name: "Bistrița-Năsăud" },
      { code: "BT", name: "Botoșani" },
      { code: "BV", name: "Brașov" },
      { code: "BR", name: "Brăila" },
      { code: "B", name: "București" },
      { code: "BZ", name: "Buzău" },
      { code: "CS", name: "Caraș-Severin" },
      { code: "CL", name: "Călărași" },
      { code: "CJ", name: "Cluj" },
      { code: "CT", name: "Constanța" },
      { code: "CV", name: "Covasna" },
      { code: "DB", name: "Dâmbovița" },
      { code: "DJ", name: "Dolj" },
      { code: "GL", name: "Galați" },
      { code: "GR", name: "Giurgiu" },
      { code: "GJ", name: "Gorj" },
      { code: "HR", name: "Harghita" },
      { code: "HD", name: "Hunedoara" },
      { code: "IL", name: "Ialomița" },
      { code: "IS", name: "Iași" },
      { code: "IF", name: "Ilfov" },
      { code: "MM", name: "Maramureș" },
      { code: "MH", name: "Mehedinți" },
      { code: "MS", name: "Mureș" },
      { code: "NT", name: "Neamț" },
      { code: "OT", name: "Olt" },
      { code: "PH", name: "Prahova" },
      { code: "SM", name: "Satu Mare" },
      { code: "SJ", name: "Sălaj" },
      { code: "SB", name: "Sibiu" },
      { code: "SV", name: "Suceava" },
      { code: "TR", name: "Teleorman" },
      { code: "TM", name: "Timiș" },
      { code: "TL", name: "Tulcea" },
      { code: "VS", name: "Vaslui" },
      { code: "VL", name: "Vâlcea" },
      { code: "VN", name: "Vrancea" },
    ],
  },
  {
    code: "RS",
    name: "Serbia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "RU",
    name: "Russian Federation",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "RW",
    name: "Rwanda",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "14", name: "Asir" },
      { code: "11", name: "Riyadh" },
      { code: "12", name: "Makkah" },
      { code: "13", name: "Eastern Province" },
      { code: "03", name: "Madinah" },
      { code: "05", name: "Qassim" },
      { code: "08", name: "Hail" },
      { code: "04", name: "Tabuk" },
      { code: "06", name: "Northern Borders" },
      { code: "09", name: "Jazan" },
      { code: "10", name: "Najran" },
      { code: "07", name: "Al Jawf" },
      { code: "01", name: "Al Bahah" },
    ],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SC",
    name: "Seychelles",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SD",
    name: "Sudan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SE",
    name: "Sweden",
    visa_support: true,
    eor_support: true,
    state_type: "county",
    states: [
      { code: "K", name: "Blekinge County" },
      { code: "W", name: "Dalarna County" },
      { code: "I", name: "Gotland County" },
      { code: "X", name: "Gävleborg County" },
      { code: "N", name: "Halland County" },
      { code: "Z", name: "Jämtland County" },
      { code: "F", name: "Jönköping County" },
      { code: "H", name: "Kalmar County" },
      { code: "G", name: "Kronoberg County" },
      { code: "BD", name: "Norrbotten County" },
      { code: "M", name: "Skåne County" },
      { code: "AB", name: "Stockholm County" },
      { code: "D", name: "Södermanland County" },
      { code: "C", name: "Uppsala County" },
      { code: "S", name: "Värmland County" },
      { code: "AC", name: "Västerbotten County" },
      { code: "Y", name: "Västernorrland County" },
      { code: "U", name: "Västmanland County" },
      { code: "O", name: "Västra Götaland County" },
      { code: "T", name: "Örebro County" },
      { code: "E", name: "Östergötland County" },
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SI",
    name: "Slovenia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SK",
    name: "Slovakia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SM",
    name: "San Marino",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SN",
    name: "Senegal",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SO",
    name: "Somalia",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SR",
    name: "Suriname",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SS",
    name: "South Sudan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SV",
    name: "El Salvador",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "SZ",
    name: "Eswatini",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TD",
    name: "Chad",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TF",
    name: "French Southern Territories",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TG",
    name: "Togo",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TH",
    name: "Thailand",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "10", name: "Bangkok" },
      { code: "11", name: "Samut Prakan" },
      { code: "12", name: "Nonthaburi" },
      { code: "13", name: "Pathum Thani" },
      { code: "14", name: "Phra Nakhon Si Ayutthaya" },
      { code: "15", name: "Ang Thong" },
      { code: "16", name: "Lopburi" },
      { code: "17", name: "Sing Buri" },
      { code: "18", name: "Chai Nat" },
      { code: "19", name: "Saraburi" },
      { code: "20", name: "Chonburi" },
      { code: "21", name: "Rayong" },
      { code: "22", name: "Chanthaburi" },
      { code: "23", name: "Trat" },
      { code: "24", name: "Chachoengsao" },
      { code: "25", name: "Prachinburi" },
      { code: "26", name: "Nakhon Nayok" },
      { code: "27", name: "Sa Kaeo" },
      { code: "30", name: "Nakhon Ratchasima" },
      { code: "31", name: "Buriram" },
      { code: "32", name: "Surin" },
      { code: "33", name: "Sisaket" },
      { code: "34", name: "Ubon Ratchathani" },
      { code: "35", name: "Yasothon" },
      { code: "36", name: "Chaiyaphum" },
      { code: "37", name: "Amnat Charoen" },
      { code: "39", name: "Nong Bua Lamphu" },
      { code: "40", name: "Khon Kaen" },
      { code: "41", name: "Udon Thani" },
      { code: "42", name: "Loei" },
      { code: "43", name: "Nong Khai" },
      { code: "44", name: "Maha Sarakham" },
      { code: "45", name: "Roi Et" },
      { code: "46", name: "Kalasin" },
      { code: "47", name: "Sakon Nakhon" },
      { code: "48", name: "Nakhon Phanom" },
      { code: "49", name: "Mukdahan" },
      { code: "50", name: "Chiang Mai" },
      { code: "51", name: "Lamphun" },
      { code: "52", name: "Lampang" },
      { code: "53", name: "Uttaradit" },
      { code: "54", name: "Phrae" },
      { code: "55", name: "Nan" },
      { code: "56", name: "Phayao" },
      { code: "57", name: "Chiang Rai" },
      { code: "58", name: "Mae Hong Son" },
      { code: "60", name: "Nakhon Sawan" },
      { code: "61", name: "Uthai Thani" },
      { code: "62", name: "Kamphaeng Phet" },
      { code: "63", name: "Tak" },
      { code: "64", name: "Sukhothai" },
      { code: "65", name: "Phitsanulok" },
      { code: "66", name: "Phichit" },
      { code: "67", name: "Phetchabun" },
      { code: "70", name: "Ratchaburi" },
      { code: "71", name: "Kanchanaburi" },
      { code: "72", name: "Suphan Buri" },
      { code: "73", name: "Nakhon Pathom" },
      { code: "74", name: "Samut Sakhon" },
      { code: "75", name: "Samut Songkhram" },
      { code: "76", name: "Phetchaburi" },
      { code: "77", name: "Prachuap Khiri Khan" },
      { code: "80", name: "Nakhon Si Thammarat" },
      { code: "81", name: "Krabi" },
      { code: "82", name: "Phangnga" },
      { code: "83", name: "Phuket" },
      { code: "84", name: "Surat Thani" },
      { code: "85", name: "Ranong" },
      { code: "86", name: "Chumphon" },
      { code: "90", name: "Songkhla" },
      { code: "91", name: "Satun" },
      { code: "92", name: "Trang" },
      { code: "93", name: "Phatthalung" },
      { code: "94", name: "Pattani" },
      { code: "95", name: "Yala" },
      { code: "96", name: "Narathiwat" },
      { code: "S", name: "Pattaya" },
    ],
  },
  {
    code: "TJ",
    name: "Tajikistan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TK",
    name: "Tokelau",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TL",
    name: "Timor-Leste",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TM",
    name: "Turkmenistan",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TN",
    name: "Tunisia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "TO",
    name: "Tonga",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TR",
    name: "Turkey",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "01", name: "Adana" },
      { code: "02", name: "Adıyaman" },
      { code: "03", name: "Afyonkarahisar" },
      { code: "04", name: "Ağrı" },
      { code: "68", name: "Aksaray" },
      { code: "05", name: "Amasya" },
      { code: "06", name: "Ankara" },
      { code: "07", name: "Antalya" },
      { code: "75", name: "Ardahan" },
      { code: "08", name: "Artvin" },
      { code: "09", name: "Aydın" },
      { code: "10", name: "Balıkesir" },
      { code: "74", name: "Bartın" },
      { code: "72", name: "Batman" },
      { code: "69", name: "Bayburt" },
      { code: "11", name: "Bilecik" },
      { code: "12", name: "Bingöl" },
      { code: "13", name: "Bitlis" },
      { code: "14", name: "Bolu" },
      { code: "15", name: "Burdur" },
      { code: "16", name: "Bursa" },
      { code: "17", name: "Çanakkale" },
      { code: "18", name: "Çankırı" },
      { code: "19", name: "Çorum" },
      { code: "20", name: "Denizli" },
      { code: "21", name: "Diyarbakır" },
      { code: "81", name: "Düzce" },
      { code: "22", name: "Edirne" },
      { code: "23", name: "Elazığ" },
      { code: "24", name: "Erzincan" },
      { code: "25", name: "Erzurum" },
      { code: "26", name: "Eskişehir" },
      { code: "27", name: "Gaziantep" },
      { code: "28", name: "Giresun" },
      { code: "29", name: "Gümüşhane" },
      { code: "30", name: "Hakkâri" },
      { code: "31", name: "Hatay" },
      { code: "76", name: "Iğdır" },
      { code: "32", name: "Isparta" },
      { code: "34", name: "İstanbul" },
      { code: "35", name: "İzmir" },
      { code: "46", name: "Kahramanmaraş" },
      { code: "78", name: "Karabük" },
      { code: "70", name: "Karaman" },
      { code: "36", name: "Kars" },
      { code: "37", name: "Kastamonu" },
      { code: "38", name: "Kayseri" },
      { code: "71", name: "Kırıkkale" },
      { code: "39", name: "Kırklareli" },
      { code: "40", name: "Kırşehir" },
      { code: "79", name: "Kilis" },
      { code: "41", name: "Kocaeli" },
      { code: "42", name: "Konya" },
      { code: "43", name: "Kütahya" },
      { code: "44", name: "Malatya" },
      { code: "45", name: "Manisa" },
      { code: "47", name: "Mardin" },
      { code: "33", name: "Mersin" },
      { code: "48", name: "Muğla" },
      { code: "49", name: "Muş" },
      { code: "50", name: "Nevşehir" },
      { code: "51", name: "Niğde" },
      { code: "52", name: "Ordu" },
      { code: "80", name: "Osmaniye" },
      { code: "53", name: "Rize" },
      { code: "54", name: "Sakarya" },
      { code: "55", name: "Samsun" },
      { code: "56", name: "Siirt" },
      { code: "57", name: "Sinop" },
      { code: "58", name: "Sivas" },
      { code: "73", name: "Şırnak" },
      { code: "59", name: "Tekirdağ" },
      { code: "60", name: "Tokat" },
      { code: "61", name: "Trabzon" },
      { code: "62", name: "Tunceli" },
      { code: "64", name: "Uşak" },
      { code: "65", name: "Van" },
      { code: "77", name: "Yalova" },
      { code: "66", name: "Yozgat" },
      { code: "67", name: "Zonguldak" },
    ],
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TV",
    name: "Tuvalu",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "TW",
    name: "Taiwan, Province of China",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "TZ",
    name: "Tanzania, United Republic of",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "UA",
    name: "Ukraine",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "UG",
    name: "Uganda",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "US",
    name: "United States of America",
    visa_support: true,
    eor_support: true,
    state_type: "state",
    states: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" },
      { code: "DC", name: "District of Columbia" },
      { code: "AS", name: "American Samoa" },
      { code: "GU", name: "Guam" },
      { code: "MP", name: "Northern Mariana Islands" },
      { code: "PR", name: "Puerto Rico" },
      { code: "VI", name: "U.S. Virgin Islands" },
    ],
  },
  {
    code: "UY",
    name: "Uruguay",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "VA",
    name: "Holy See (Vatican City State)",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "VE",
    name: "Venezuela, Bolivarian Republic of",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "VG",
    name: "Virgin Islands, British",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "VI",
    name: "Virgin Islands, U.S.",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "VN",
    name: "Viet Nam",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "44", name: "An Giang" },
      { code: "43", name: "Ba Ria - Vung Tau" },
      { code: "54", name: "Bac Giang" },
      { code: "53", name: "Bac Kan" },
      { code: "55", name: "Bac Lieu" },
      { code: "56", name: "Bac Ninh" },
      { code: "50", name: "Ben Tre" },
      { code: "31", name: "Binh Dinh" },
      { code: "57", name: "Binh Duong" },
      { code: "58", name: "Binh Phuoc" },
      { code: "40", name: "Binh Thuan" },
      { code: "59", name: "Ca Mau" },
      { code: "CT", name: "Can Tho" },
      { code: "04", name: "Cao Bang" },
      { code: "33", name: "Dak Lak" },
      { code: "72", name: "Dak Nong" },
      { code: "71", name: "Dien Bien" },
      { code: "39", name: "Dong Nai" },
      { code: "45", name: "Dong Thap" },
      { code: "30", name: "Gia Lai" },
      { code: "03", name: "Ha Giang" },
      { code: "63", name: "Ha Nam" },
      { code: "HN", name: "Ha Noi" },
      { code: "23", name: "Ha Tinh" },
      { code: "61", name: "Hai Duong" },
      { code: "HP", name: "Hai Phong" },
      { code: "73", name: "Hau Giang" },
      { code: "SG", name: "Ho Chi Minh" },
      { code: "14", name: "Hoa Binh" },
      { code: "66", name: "Hung Yen" },
      { code: "34", name: "Khanh Hoa" },
      { code: "47", name: "Kien Giang" },
      { code: "28", name: "Kon Tum" },
      { code: "01", name: "Lai Chau" },
      { code: "35", name: "Lam Dong" },
      { code: "09", name: "Lang Son" },
      { code: "02", name: "Lao Cai" },
      { code: "41", name: "Long An" },
      { code: "67", name: "Nam Dinh" },
      { code: "22", name: "Nghe An" },
      { code: "18", name: "Ninh Binh" },
      { code: "36", name: "Ninh Thuan" },
      { code: "68", name: "Phu Tho" },
      { code: "32", name: "Phu Yen" },
      { code: "24", name: "Quang Binh" },
      { code: "27", name: "Quang Nam" },
      { code: "29", name: "Quang Ngai" },
      { code: "13", name: "Quang Ninh" },
      { code: "25", name: "Quang Tri" },
      { code: "52", name: "Soc Trang" },
      { code: "05", name: "Son La" },
      { code: "37", name: "Tay Ninh" },
      { code: "20", name: "Thai Binh" },
      { code: "69", name: "Thai Nguyen" },
      { code: "21", name: "Thanh Hoa" },
      { code: "26", name: "Thua Thien Hue" },
      { code: "46", name: "Tien Giang" },
      { code: "51", name: "Tra Vinh" },
      { code: "07", name: "Tuyen Quang" },
      { code: "49", name: "Vinh Long" },
      { code: "70", name: "Vinh Phuc" },
      { code: "06", name: "Yen Bai" },
    ],
  },
  {
    code: "VU",
    name: "Vanuatu",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "WS",
    name: "Samoa",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "YE",
    name: "Yemen",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "YT",
    name: "Mayotte",
    visa_support: false,
    eor_support: false,
    state_type: null,
    states: [],
  },
  {
    code: "ZA",
    name: "South Africa",
    visa_support: true,
    eor_support: true,
    state_type: "province",
    states: [
      { code: "EC", name: "Eastern Cape" },
      { code: "FS", name: "Free State" },
      { code: "GP", name: "Gauteng" },
      { code: "KZN", name: "KwaZulu-Natal" },
      { code: "LP", name: "Limpopo" },
      { code: "MP", name: "Mpumalanga" },
      { code: "NC", name: "Northern Cape" },
      { code: "NW", name: "North West" },
      { code: "WC", name: "Western Cape" },
    ],
  },
  {
    code: "ZM",
    name: "Zambia",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    visa_support: true,
    eor_support: true,
    state_type: null,
    states: [],
  },
]

// Utility functions
export const getCountryByCode = (code: string): CountryInfo | null => {
  return allCountries.find((country) => country.code === code) || null
}

export const getCountryByName = (name: string): CountryInfo | null => {
  return allCountries.find((country) => country.name === name) || null
}

export const getCurrencyForCountry = (countryCode: string): string => {
  return countryCurrencyMapping[countryCode] || "USD"
}

export const getCurrencyInfo = (currencyCode: string): Currency | null => {
  return allCurrencies.find((currency) => currency.code === currencyCode) || null
}

export const getStatesForCountry = (countryCode: string): CountryState[] => {
  const country = getCountryByCode(countryCode)
  return country?.states || []
}

export const hasStates = (countryCode: string): boolean => {
  const country = getCountryByCode(countryCode)
  return !!(country?.state_type && country.states.length > 0)
}

export const getStateTypeLabel = (countryCode: string): string => {
  const country = getCountryByCode(countryCode)
  if (country?.state_type === "state") return "State"
  if (country?.state_type === "province") return "Province"
  if (country?.state_type === "prefecture") return "Prefecture"
  if (country?.state_type === "region") return "Region"
  if (country?.state_type === "canton") return "Canton"
  if (country?.state_type === "emirate") return "Emirate"
  if (country?.state_type === "county") return "County"
  if (country?.state_type === "country") return "Country"
  if (country?.state_type === "district") return "District"
  if (country?.state_type === "voivodeship") return "Voivodeship"
  return "State/Province"
}

export const getAvailableCountries = (): string[] => {
  return allCountries
    .filter((country) => country.eor_support)
    .map((country) => country.name)
    .sort()
}

export const getEORSupportedCountries = (): CountryInfo[] => {
  return allCountries.filter((country) => country.eor_support)
}
